import * as repo from "./aiUsage.repository.js";

/**
 * Calculate the cost of the OpenAI request based on token counts
 * Pricing:
 *   - Input Tokens: $0.40 per 1,000,000 tokens
 *   - Output Tokens: $1.60 per 1,000,000 tokens
 * @param {number} promptTokens 
 * @param {number} completionTokens 
 * @returns {number} Cost in USD rounded to 6 decimals
 */
export const calculateCost = (promptTokens = 0, completionTokens = 0) => {
  const inputCost = (promptTokens / 1000000) * 0.40;
  const outputCost = (completionTokens / 1000000) * 1.60;
  const totalCost = inputCost + outputCost;
  return Number(totalCost.toFixed(6));
};

/**
 * Log a new AI request usage in database
 * @param {Object} data 
 * @returns {Promise<Object>}
 */
export const createUsage = async (data) => {
  const promptTokens = data.promptTokens || 0;
  const completionTokens = data.completionTokens || 0;

  // Auto-calculate totalTokens if not provided
  if (data.totalTokens === undefined || data.totalTokens === null) {
    data.totalTokens = promptTokens + completionTokens;
  }

  // Auto-calculate cost if not provided
  if (data.cost === undefined || data.cost === null) {
    data.cost = calculateCost(promptTokens, completionTokens);
  }

  return repo.createUsage(data);
};

/**
 * Get aggregated dashboard statistics
 * @returns {Promise<Object>}
 */
export const getDashboardStats = async () => {
  return repo.getDashboardStats();
};

/**
 * Get recent AI request logs
 * @param {number} limit 
 * @returns {Promise<Array>}
 */
export const getRecentLogs = async (limit) => {
  return repo.getRecentLogs(limit);
};

/**
 * Get top users generating the most AI trips
 * @param {number} limit 
 * @returns {Promise<Array>}
 */
export const getTopUsers = async (limit) => {
  return repo.getTopUsers(limit);
};

/**
 * Get most used AI models sorted descending by requests
 * @returns {Promise<Array>}
 */
export const getMostUsedModels = async () => {
  return repo.getMostUsedModels();
};

/**
 * Get top destinations generated by AI
 * @param {number} limit 
 * @returns {Promise<Array>}
 */
export const getTopDestinations = async (limit) => {
  return repo.getTopDestinations(limit);
};

/**
 * List AI usage logs with filtering and pagination
 * @param {Object} options
 * @param {number} options.page
 * @param {number} options.limit
 * @param {string} options.feature
 * @param {string} options.userId
 * @param {string} options.status
 * @param {string} options.from
 * @param {string} options.to
 * @returns {Promise<Object>}
 */
export const listUsage = async ({ page = 1, limit = 20, feature, userId, status, from, to }) => {
  return repo.listUsage({ page, limit, feature, userId, status, from, to });
};

/**
 * Get AI usage statistics aggregated by feature
 * @param {Object} options
 * @param {string} options.from
 * @param {string} options.to
 * @returns {Promise<Array>}
 */
export const getUsageStats = async ({ from, to }) => {
  return repo.getUsageStats({ from, to });
};

/**
 * Get a single AI usage log by ID
 * @param {string} id
 * @returns {Promise<Object|null>}
 */
export const getUsageById = async (id) => {
  return repo.getUsageById(id);
};